options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: test
    name: golang:1.22
    entrypoint: go
    args: ["build", "./..."]

  - id: build
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_IMAGE_URI}", "."]

  - id: push
    name: gcr.io/cloud-builders/docker
    args: ["push", "${_IMAGE_URI}"]

  - id: deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - ${_SERVICE_NAME}
      - --image=${_IMAGE_URI}
      - --region=${_REGION}
      - --platform=managed
      

substitutions:
  _REGION: southamerica-east1
  _SERVICE_NAME: low-carbon-notification-service
  _IMAGE_URI: southamerica-east1-docker.pkg.dev/low-carbon-491109/low-carbon/notification-service:${SHORT_SHA}
